### ISSUE TITLE
how to add epsilonMOEA algorithm in moea framework

### ISSUE THREAD

**Issue by ridasardaar** [MOEAFramework/MOEAFramework#119]
i am using this code:
NondominatedPopulation result = new Executor()
				.withProblemClass(Knapsack.class, input)
				.withAlgorithm("epsilonMOEA")
				.withProperty("population", 100 )
				.withMaxEvaluations(50000)
				.distributeOnAllCores()
				.run();
but it gives this error:
multiple constraints not supported, aggregating into first constraint
Exception in thread "main" org.moeaframework.core.spi.ProviderNotFoundException: no provider for newGDE3
	at org.moeaframework.core.spi.AlgorithmFactory.getAlgorithm(AlgorithmFactory.java:159)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:785)
	at org.moeaframework.Executor.run(Executor.java:743)
	at org.moeaframework.examples.ga.knapsack.KnapsackExample.main(KnapsackExample.java:90)

**Comment by ridasardaar** [comment]
i want to use GDE3, epsilonMOEA and IBEA algorithms but facing the same problem. Plese anyone know solution for this issue help me.

**Comment by dhadka** [comment]
Hi,

EpsilonMOEA is supported for the Knapsack problem, but you must use the name "eMOEA":

```java

		NondominatedPopulation result = new Executor()
				.withProblemClass(Knapsack.class, input)
				.withAlgorithm("eMOEA")
				.withProperty("population", 100 )
				.withMaxEvaluations(50000)
				.distributeOnAllCores()
				.run();
```

GDE3 is not supported because it can only work on real-valued problems (knapsack using a binary string encoding).  IBEA will not work on the Knapsack problem because this implementation of IBEA does not support constraints.

Please check the [List of Algorithms](http://moeaframework.org/javadoc/overview-summary.html#listOfAlgorithms) to determine the name and supported types.

**Comment by ridasardaar** [comment]
OK thank you.
