### ISSUE TITLE
solution.getconstrains();

### ISSUE THREAD

**Issue by CumaliTurkmenoglu** [MOEAFramework/MOEAFramework#122]
My issue:
I can NOT get the constraints of the solution neither by getConstraints() nor by getConstraint() in evaluate() method while no problem with other methods of the solution (getVariable(0),getObjectives())
It does not throw any exeption and stuck there. I cant figure out the problem! :(
```
 @Override
    public void evaluate(Solution solution) {
        int[] d = EncodingUtils.getPermutation(solution.getVariable(0));
        double[] f = new double[2];
        double [] constraints=new double[nConst];
        constraints=solution.getConstraints(); ????????? stucks in the method
```

**Comment by dhadka** [comment]
Hi,

I'm not too sure what you mean by it gets stuck there.  Please try the following suggestion, but if it doesn't fix the issue, please post the full code so I can try to replicate the issue here.  Thanks!

The `getConstraints()` method returns a **copy** of the array, so if you modify the `constraints` array it will **not** change the constraint values within the solution.  Instead, it should look as follows.  Create the `constraints` array, then populate its values, and finally call `solution.setConstraints(constraints)`.

```java
@Override
public void evaluate(Solution solution) {
        int[] d = EncodingUtils.getPermutation(solution.getVariable(0));
        double[] f = new double[2];
        double[] constraints = new double[nConst];
        ....
        constraints[0] = ...
        constraints[1] = ...
        ....
        solution.setConstraints(constraints);
}
```

**Comment by CumaliTurkmenoglu** [comment]
l can not debug the code to determine the problem since it stuck at the line where getConstraints method is called. No problem with setting the constrains.
