### ISSUE TITLE
runSeeds, random seeds, and multi-threaded reproducibility

### ISSUE THREAD

**Issue by fstonedahl** [MOEAFramework/MOEAFramework#127]
I was rather expecting the runSeeds() method to run N specific random-seeds, and to do so in a reproducible way.  More specifically, it surprised me that this protected method:

`Executor.runSingleSeed(int seed, int numberOfSeeds,TerminationCondition terminationCondition)`

doesn't appear to be using the `seed ` value at all, even though it is passed in.  (I guess that subclasses could change that behavior if they wished.)

Anyway, it appears that I can get reproducible single-threaded behavior by calling `PRNG.setSeed()` before starting the Executor running.  Do you have any thoughts about getting reproducible behavior in multi-threaded runs?  

Since my Problem is a simulation that needs a random seed to run reproducibly , I am vaguely imagining an Executor handing out random seeds to each distributed evaluate() call in some deterministic manner... perhaps by making subclasses of both FutureSolution and DistributedProblem?  Not clear.  It's seeming hard/messy, so it may not be worth the trouble, but I'd be glad to hear your thoughts!

**Comment by dhadka** [comment]
Yes, the `seed` argument in `runSingleSeed` just tells it which run, `1` to `numberOfSeeds`, it's currently running.  I believe I originally added that to allow for reporting progress, but that's now handled in the `runSeeds` method.

If you're using the `Executor.distributeOnAllCores()` or `DistributedProblem` to parallelize evaluations, it *should* still be reproducible unless the problem's `evaluate` method uses the PRNG random number generator.  The reason is that we are only parallelizing evaluations.  The main loop for the algorithm (parent selection, crossover/mutation, survival selection, etc.) still runs serially.  I would recommend testing though as there may be some other aspect I'm not considering.

If you want to parallelize runs, such as running two or more algorithms simultaneously or running the same algorithm with different seeds in parallel, it should be possible using a "thread local" random number generator.  Here's an example: https://gist.github.com/dhadka/f5a3adc36894cc6aebcaf3dc1bbcef9f.  Each thread gets assigned its own random number generator with its own seed.  At the beginning of your code, put:

```java

PRNG.setRandom(SynchronizedMersenneTwister.getInstance());
```

Then, you simply spawn multiple threads and run the algorithms (e.g., using the Executor).  Each thread is initialized with a random seed produced by the `SEEDER`.  You can also call `PRNG.setSeed` on each thread...it will only change the seed on the caller's thread.  Again, I would recommend testing first as I haven't extensively checked for reproducibility.

**Comment by fstonedahl** [comment]
Thanks for the detailed answer!

My issue is that the problem evaluation is a non-deterministic simulation, so I need to provide *some* random seed each time the problem's evaluate method is called.  Even if I don't touch the MOEA PRNG, and use my own RNG to seed each simulation, it will get invoked in a different order depending on the non-deterministic order that threads are run.

One solution would be to get access to the order in which the FutureSolutions had their evaluations *requested*, since that should be consistent (since the main algorithm loops run serially, as you noted).

I went ahead and added this functionality to my fork (along with a unit test demonstrating it), and I will issue a pull request, where we can discuss this further as needed.
