### ISSUE TITLE
Using Program for more than one decision variable

### ISSUE THREAD

**Issue by toluboltz** [MOEAFramework/MOEAFramework#155]
Hello David,

Is it possible to use program for more than one decision variable. For example, if I were to solve the ant problem but instead using more than one ant. How will I approach this problem? Thank you.

**Comment by dhadka** [comment]
Yes, you can have more than one in a solution.  The newSolution() method needs to create a solution with the program(s):

```java

	public Solution newSolution() {
		Solution solution = new Solution(2, nobjs);
		solution.setVariable(0, new Program(rules));
		solution.setVariable(1, new Program(rules));
		return solution;
	}
```

and the evaluate method can then use these programs:

```java

	public synchronized void evaluate(Solution solution) {
		int nants = 2;
		Program[] programs = new Program[nants];

		for (int i = 0; i < nants; i++)
			programs[i] = (Program)solution.getVariable(i);
		
		world.reset();
		
		while ((world.getRemainingMoves() > 0) &&
				(world.getRemainingFood() > 0)) {
			for (int i = 0; i < nants; i++) {
				Environment environment = new Environment();
				environment.set("world", world);
				environment.set("currentAnt", i);
				programs[i].evaluate(environment);
			}
		}
		
		...
	}
```

You'll need some way to indicate which ant is currently active so that we know which ant is performing the action.  In my example above, I'm assuming you set a variable with  `world.setCurrentAnt(i)`.  Then, when the program calls an action, such as world.moveForward(), it knows which ant is performing that action.

**Comment by toluboltz** [comment]
Thanks David.

**Comment by toluboltz** [comment]
Hello David, 

I'm getting the error and can't seem to figure out the problem

Exception in thread "main" org.apache.commons.math3.exception.NotStrictlyPositiveException: 0 is smaller than, or equal to, the minimum (0)
	at org.apache.commons.math3.random.BitsStreamGenerator.nextInt(BitsStreamGenerator.java:154)
	at org.apache.commons.math3.random.RandomAdaptor.nextInt(RandomAdaptor.java:158)
	at org.moeaframework.core.PRNG.nextInt(PRNG.java:153)
	at org.moeaframework.core.PRNG.nextItem(PRNG.java:363)
	at org.moeaframework.util.tree.Rules.buildTreeFull(Rules.java:487)
	at org.moeaframework.util.tree.Rules.buildTreeFull(Rules.java:490)
	at org.moeaframework.core.variable.Program.randomize(Program.java:89)
	at org.moeaframework.core.operator.RandomInitialization.initialize(RandomInitialization.java:62)
	at org.moeaframework.algorithm.AbstractEvolutionaryAlgorithm.initialize(AbstractEvolutionaryAlgorithm.java:97)
	at org.moeaframework.algorithm.AbstractAlgorithm.step(AbstractAlgorithm.java:159)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:816)
	at org.moeaframework.Executor.run(Executor.java:743)
	at com.tolu.program.StaticEvaderExample.main(StaticEvaderExample.java:17)

**Comment by dhadka** [comment]
Thanks for reporting this.  I added better error messages for this situation.  Please pull the latest master and run the code again.

Essentially, while it's trying to construct the program, it's unable to find a valid argument for some function.  For example, suppose our Rules were setup as follows:

```java

		Rules rules = new Rules();
		rules.add(new Add());
		rules.add(new Constant(false));
		rules.add(new Constant(true));
```

When it goes to create the Add function, which needs two numeric arguments, it fails because there are no valid nodes.  All we have are two boolean constants: true and false.  We can fix this by adding a rule that produces a numeric result, say reading the value of a variable:

```java

		Rules rules = new Rules();
		rules.add(new Add());
		rules.add(new Constant(false));
		rules.add(new Constant(true));
		rules.add(new Get(Number.class, "x")); // Variable x, which is a number
```

With the change I just committed, you'll now see error messages like:

    Unable to find valid argument for Add
    No terminal found with type Number

which should help identify the problem.  You'll then need to add whatever function(s) or terminal(s) that are needed so it can generate "complete" programs.

**Comment by toluboltz** [comment]
Thank you. I have identified the problem.

**Comment by toluboltz** [comment]
Please I'm trying to combine subset encoding and program encoding. Basically, using the ant problem example, I want to pick out of a number of ants who have different starting positions and run the ant game. And get my answer as the best ants to pick and print out their paths
