### ISSUE TITLE
Problem regarding getting list of population generated in a problem

### ISSUE THREAD

**Issue by Amit-1984** [MOEAFramework/MOEAFramework#160]
A great greetings to all,
i am using Executor to configure and run an algorithm on custom problem. I want to store all the initial and intermediate population generated into a seprate file. 
Kindly help me in this direction.

Thanks in advance.

**Comment by Amit-1984** [comment]
Anyone kindly help 
it is urgent for me.

**Comment by dhadka** [comment]
Hi, this requires creating a custom Collector to use with the Instrumenter.  For example:

```java

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.moeaframework.Executor;
import org.moeaframework.Instrumenter;
import org.moeaframework.analysis.collector.Accumulator;
import org.moeaframework.analysis.collector.AttachPoint;
import org.moeaframework.analysis.collector.Collector;
import org.moeaframework.core.EvolutionaryAlgorithm;
import org.moeaframework.core.Solution;
import org.moeaframework.core.variable.EncodingUtils;

public class CollectPopulationExample {
	
	public static class PopulationCollector implements Collector {
		
		private final EvolutionaryAlgorithm algorithm;
		
		public PopulationCollector() {
			this(null);
		}
		
		public PopulationCollector(EvolutionaryAlgorithm algorithm) {
			super();
			this.algorithm = algorithm;
		}

		@Override
		public AttachPoint getAttachPoint() {
			return AttachPoint.isSubclass(EvolutionaryAlgorithm.class).and(
					AttachPoint.not(AttachPoint.isNestedIn(
							EvolutionaryAlgorithm.class)));
		}

		@Override
		public Collector attach(Object object) {
			return new PopulationCollector(
					(EvolutionaryAlgorithm)object);
		}

		@Override
		public void collect(Accumulator accumulator) {
			ArrayList<Solution> list = new ArrayList<Solution>();
			
			for (Solution solution : algorithm.getPopulation()) {
				list.add(solution);
			}
			
			accumulator.add("Population", list);
		}

	}

	public static void main(String[] args) throws IOException {
		Instrumenter instrumenter = new Instrumenter()
				.withProblem("UF1")
				.withFrequency(100)
				.attach(new PopulationCollector());
		
		new Executor()
				.withProblem("UF1")
				.withAlgorithm("NSGAII")
				.withMaxEvaluations(10000)
				.withInstrumenter(instrumenter)
				.run();
		
		Accumulator accumulator = instrumenter.getLastAccumulator();
		
		for (int i=0; i<accumulator.size("NFE"); i++) {
			System.out.println("NFE: " + accumulator.get("NFE", i));
			ArrayList<Solution> solutions = (ArrayList<Solution>)accumulator.get("Population", i);
			
			for (Solution s : solutions) {
				double[] vars = EncodingUtils.getReal(s);
				System.out.println("  " + Arrays.toString(vars) + " => " + Arrays.toString(s.getObjectives()));
			}
			
			System.out.println();
		}
	}

}
```

**Comment by fchgithub** [comment]
Hi @dhadka 
I've added moea framework to my Maven dependency. I see that PopulationCollector.java has been added to the project 2 days ago. But I cannot create an instance from it with the current maven setting. Is there anything I can do to use it?

**Comment by Amit-1984** [comment]
Thanks @dhadka for your kind reply
it is very helpful for me and i am working on it to customize it to my requirements.
I also want to read about "Collector" & its working in more details. So, can you please refer me in this direction too.....
Moreover, i have one more question:
i want to put finally block in my code (Actually, i have defined a custom problem in a separate A.java file and running the moea using another run class defined as another B.java file. My A.java file contain logic to represent the problem and methods to define the population. In this code i want to store the generated populations into a separate output file. Here i have defined a finally block which closes the stream associated with my output file (.txt). But after run is over, this .txt file is blank and probably my finally block is not executing, keeping the stream open.
Where in moea execution my finally block should be placed? So that the output stream is closed after run is completed and my .txt file contain text written into it.


Thanks in advance.

**Comment by dhadka** [comment]
@fchgithub Regarding the Maven dependency, I'm not sure if you can link it directly to a GitHub commit/branch.  The easiest solution is probably to just copy PopulationCollector.java into your code and use it that way.

**Comment by dhadka** [comment]
@Amit-1984 I'm not aware of any documentation on collectors.  The best way to learn is probably to look at the source code and some of the existing collectors: https://github.com/MOEAFramework/MOEAFramework/tree/master/src/org/moeaframework/analysis/collector

Could you please share your example of using the try-catch-finally?  The finally block will always run after the try block finishes executing...so unless something within the try block is still running, it should call the close method.

**Comment by Amit-1984** [comment]
First of all, thanks for the help. I have further question in the solution suggested:
Does the class EvolutionaryAlgorithm in the line "private final EvolutionaryAlgorithm algorithm;" needs to be replaced by the algorithm that we are going to implement/ use say nsga-iii. Moreover, it will be helpful for me if you kindly explain what is going on in the solution provided by you (PopulationCollector.java) (i am unable to find where those initial and intermediate populations are stored and how they are being printed in the main function.

Thanks

**Comment by dhadka** [comment]
Hi @Amit-1984, 

> Does the class EvolutionaryAlgorithm in the line "private final EvolutionaryAlgorithm algorithm;" needs to be replaced by the algorithm that we are going to implement/ use say nsga-iii.

For most cases, no.  We use `EvolutionaryAlgorithm` since it has the `getPopulation` method.  Most algorithms, like NSGA-II and NSGA-III are subclasses of `EvolutionaryAlgorithm`, so they will work as-is.

> Moreover, it will be helpful for me if you kindly explain what is going on in the solution provided by you (PopulationCollector.java) (i am unable to find where those initial and intermediate populations are stored and how they are being printed in the main function.

This gets a bit complex, but the gist of it is that the Instrumenter will scan the optimization algorithm and "attach" the collector, in this case the `PopulationCollector`, where needed.  The `getAttachPoint` method describes what the collector is attaching to, in this example it will attach to any `EvolutionaryAlgorithm`.  As the optimization algorithm is running, it will call the `collect` method to record the data in an `Accumulator` object.  This `Accumulator` just stores time-series data that you can query with a key and an index.  The main function is just walking through these time-series and displaying the data.  E.g., `accumulator.get("NFE", i)` returns the i-th data point in the NFE time-series.  Similar for `accumulator.get("Population", i)`.

Please feel free to ask more specific questions.

**Comment by Amit-1984** [comment]
I tried implementing the solution provided by @dhadka in https://github.com/MOEAFramework/MOEAFramework/issues/160#issuecomment-372143306. I have following points to clarify:-
1) .withFrequency(100)- i think this function sets after how many population the data needs to be saved. I tried setting it to one in order to store every population generated. But, always results are printed for NFE = 100.
2) i tried setting .withProperty("populationSize",10)- with other conditions same mainly .withFrequency as 100. it prints results as NFE = 10 NFE =20 & so on. I think, NFE is somewhat releated to population size.
3) what if i want to print the population iteration wise. then in what direction i need to work.

Thanks in advance.

**Comment by dhadka** [comment]
1. One important thing to note here is that `withFrequency` is not guaranteed, it's more of a hint.  The reason for this is that we only record the data after an iteration of the algorithm.  For some algorithms, like NSGA-II, one iteration involves evaluating the entire population.  So if you set `withFrequency(10)` but the population size is 100, it will still only print every 100 NFE because that's one iteration.

2. Can you please double-check this?  I would expect if you set the population size to 10 and ran with a frequency of 100, you would only see the output every 100 NFE.  Using the code from above, I ran the following scenarios:

    1. `withFrequency(10)` and `withProperty("populationSize", 10)` - Prints every 10 NFE - OK
    2. `withFrequency(10)` and `withProperty("populationSize", 100)` - Prints every 100 NFE - OK
    3. `withFrequency(100)` and `withProperty("populationSize", 10)` - Prints every 100 NFE - OK

3. Set `withFrequencyType(FrequencyType.STEPS)` on the `Instrumenter`.  Then, `withFrequency(100)` would mean collect data every 100 iterations (steps).
