### ISSUE TITLE
Missing nondominating Solution in final Population 

### ISSUE THREAD

**Issue by randUsr** [MOEAFramework/MOEAFramework#161]
I'm running the NSGA-II algorithm and I noticed, that in early steps of the algorithm i get 3 Nondominating Solutions with `algorithm.getResult()` and in later steps the resulting Population contains only 2 Solutions.
My guess is, the third solution is kicked from the population when generating a new Generation.
But this is messing up the Hypervolume measurement and others, isn't it?
In my understanding all nondominating solutions should be saved and given with `.getResult()`, regardless in which evolutionary step they where generated.

This may affect #116

**Comment by dhadka** [comment]
Thanks for reporting this.

In this code, the value returned by getResult() depends on the algorithm and whether it uses an archive.  For example, NSGA-II does not have an archive (by default), so getResult() returns the non-dominated solutions in the final population.  It's the responsibility of NSGA-II's survival selection (non-dominated sorting by rank and crowding distance) to determine what solutions it keeps each iteration.

If you instead run NSGA-II with an archive, then getResult() returns the contents of the archive, which contains all nondominated solutions generated throughout the entire run.

What is odd though is if you're using a population size of 100 and only have 3 non-dominated solutions, then the 3 non-dominated solutions should always survive to the next iteration since they would be rank 0.  I would expect this to happen only when it generates a new child that dominated two of the three original non-dominated solutions and thus replaced them.  Do you happen to know the objective values for the three original non-dominated solutions and the two that appear in the final result?

**Comment by dhadka** [comment]
Also just to add: Unless the number of non-dominated solutions in the combined population (current population + offspring) exceeds the population size, then NSGA-II will maintain all non-dominated solutions each iteration.

**Comment by randUsr** [comment]
The objective of the solutions are: 
[-0.094,	-2] [-0.030, -7] [-0.092, -5]
and in the next generation only the solutions with thes objectives survive:
[-0.056, -7] [-0.119, -5]
So you are right the new solution  [-0.119, -5] dominates both! Sorry my fault.
And this won't affect hypervolume, too

**Comment by lmrkela** [comment]
So, if we have population of 100 and more than 100 non-dominated solutions some solutions will be lost unless we use the archive? But does using the archive changes the nature of NSGA-2 algorithm or it remains the same?

**Comment by dhadka** [comment]
@lmrkela Yes, some non-dominated solutions will be lost unless an archive is used.  It also depends on which archive you use. `NondominatedPopulation` will store all non-dominated solutions, but the others will not.

For NSGA-2, the behavior is unchanged when using the archive.

**Comment by lmrkela** [comment]
@dhadka  Thank you on very fast answering! 

I used attachApproximationSetCollector for Instrumenter and collected sets from all iterations to one non-dominated population (and missing solutions appeared). Can this be used as alternative to archive?

**Comment by dhadka** [comment]
Assuming you're getting the set from each iteration, then it should be a good alternative for NSGA-2.
