### ISSUE TITLE
Injecting custom solutions and use MOEA algorithms to produce the next generation

### ISSUE THREAD

**Issue by msukumaran** [MOEAFramework/MOEAFramework#163]
Hi Mr. Hadka and Everyone, 

I’m trying to evaluate a problem externally. This means that I have an external program that creates a population of solutions as well as their corresponding objectives. (example GEN0: A population of 100 individuals with each solution having 3 decision variables and 3 objectives, and the objective values are already calculated externally and outputs them as a json file.)
Through reading other issues here, I have managed to inject my solutions and their corresponding objectives as my initial population. (using InjectedInitialization, slightly modified so that solutions are read from a json file.) I’ve done this using the guide of Chapter 5 in the Beginner's Guide to the MOEA Framework. IF I have understood correctly, since my objective values are calculated externally, the evaluate (Solution solution) function in my OwnProblem class is basically empty. Have I understood this correctly?

When i try to run an algorithm for 2 evaluations. (meaning only to get the next generation GEN1..?) What I get as a result only the selecting of the best solution from my injectedSolutions of GEN0. However, what I am expecting is that I get only the next generation of solutions GEN1 (unevaluated), so that I can feed this GEN1 of solution to the external program to be evaluated. Then I would inject the new solutions (GEN1) with their evaluated objectives back to the population to generate the next (GEN2) and so on.

I hope my current problem is somewhat clear.. if not I’m happy to share my code or explain further.
Any ideas or help is much appreciated! Thanks in advance!

**Comment by dhadka** [comment]
**Since my objective values are calculated externally, the evaluate (Solution solution) function in my OwnProblem class is basically empty. Have I understood this correctly?**

Typically you would need something in the evaluate method to pass the decision variables to your external program and read the resulting JSON output.

Or are you calling your external program elsewhere?

**When i try to run an algorithm for 2 evaluations. (meaning only to get the next generation GEN1..?) What I get as a result only the selecting of the best solution from my injectedSolutions of GEN0. However, what I am expecting is that I get only the next generation of solutions GEN1 (unevaluated), so that I can feed this GEN1 of solution to the external program to be evaluated. Then I would inject the new solutions (GEN1) with their evaluated objectives back to the population to generate the next (GEN2) and so on.**

If I understand correctly, you're staying that since the initial population generated by InjectedInitialization already has their objectives evaluated and assigned, it shouldn't send them to be evaluated again.

This behavior is essentially by design, if you look at [AbstractEvolutionaryAlgorithm.java](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/AbstractEvolutionaryAlgorithm.java).

```java

	protected void initialize() {
		super.initialize();

		Population population = getPopulation();
		NondominatedPopulation archive = getArchive();
		Solution[] initialSolutions = initialization.initialize();
		
		evaluateAll(initialSolutions); // Initial population is always sent for evaluation
		population.addAll(initialSolutions);

		if (archive != null) {
			archive.addAll(population);
		}
	}
```

Unfortunately, the Solution class doesn't have any flag telling you that it's been evaluated or not, which is why it evaluates the solutions even if you assigned the objective values.

There are a few options you could take.

1. Subclass the algorithm and override the initialize method to not evaluate the initial population.  This isn't great because you'd need to provide your own `initialize()` implementation for each algorithm you want to run.

2. Implement some logic in your problem's `evaluate(Solution)` method to skip evaluating these initial solutions.  For example, your InjectedInitialization subclass can assign the attribute:

    ```java

    solution.setAttribute("IS_EVALUATED", true);
    ```

    And in your Problem subclass:

    ```java

    public void evaluate(Solution solution) {
        if (solution.hasAttribute("IS_EVALUATED") && (Boolean)solution.getAttribute("IS_EVALUATED")) {
            return; // Solution already evaluated, skip.
        }

        // Otherwise, send the solution to be evaluated.
        super.evaluate(solution);
    }
    ```

    This approach works because attributes are not copied when you create a copy of a solution.  So when a variation operator is creating the offspring, it will not copy over any attributes.

**Comment by msukumaran** [comment]
Hi, 
A huge thanks for replying so quickly! 
Yea it makes more sense to use your idea of logic implementation. I'm going to try that out.

**If I understand correctly, you're staying that since the initial population generated by InjectedInitialization already has their objectives evaluated and assigned, it shouldn't send them to be evaluated again.**

yes correct. This is perhaps a simpler (less elegant) way of solving my problem.

My initial idea was actually based on a previous post here.
Extending MOEA with a simulation
https://github.com/MOEAFramework/MOEAFramework/issues/157

In the evaluate method to call my program with the decision variables as arguments and the program should return the objectives and this would then be set for each solution. 
However since my external program is written in python it would take some know how to call a python from java. In your opinion, would this be a plausible approach?
Or are there some other ways which i am overlooking?

**Comment by msukumaran** [comment]
hi, 
just a quick update, i managed to extend the MOEA Framework with my external program to evaluate the solutions and get the objectives back. 
Thanks alot for your help and feedback!
