### ISSUE TITLE
Invalidating or removing a particular solution from generated population

### ISSUE THREAD

**Issue by Amit-1984** [MOEAFramework/MOEAFramework#169]
A great greeting to all first.........
my question is that is it possible to invalidate or remove a particular solution (present in the form of chromosome) based on particular user defined condition, so that in next iterations, the particular solution will not took participation if it does not fulfil the condition and thus help to achieve the optimization faster.....
Correct me if i am wrong and guide me if possible.

Thanks in advance

**Comment by dhadka** [comment]
The easy way is to set a large constraint value on these invalid solutions.  Solutions with smaller constraint violations will always be selected preferentially.  Additionally, when truncating the population at the end of each iteration, solutions with smaller constraint violations will survive to the next generation.  Invalid solutions will tend to "die off" over time due to lack of selection / survival.  You can make this modification in your problem's evaluate method.

However, this easy way does not guarantee that these invalid solutions will not participate.  It just makes it less likely as it will always prefer solutions with smaller constraint violations.

There are some other options you could consider as well, such as changing the encoding to one that enforces the condition, introducing a "repair" step to fix solutions violating the condition, seeding the initial population with a few good solutions, etc.
