### ISSUE TITLE
Using the instrumenter for Custom problems (no reference set available)

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#181]
Hi @dhadka 

1) From the beginner's guide, I understand that one can use the instrumenter without explicitly specifying a reference set in a custom problem. I get the error below when I try to run my problem (#176) without specifying the set (my problem is such that I can't know this apriori). Please see my  instrumenter below; commented lines give the error leaving me with an empty plot, when I use the plotter.

Error
```Java
Exception in thread "main" java.lang.IllegalArgumentException: no reference set available
	at org.moeaframework.ProblemBuilder.getReferenceSet(ProblemBuilder.java:274)
	at org.moeaframework.Instrumenter.getReferenceSet(Instrumenter.java:549)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:686)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:804)
	at org.moeaframework.Executor.run(Executor.java:743)
	at org.matsim.onnene.ga.RunSimulationBasedTransitOptimizationProblem.main(RunSimulationBasedTransitOptimizationProblem.java:120)
```

Instrumenter:

```java
        Instrumenter instrumenter = new Instrumenter();       	
                instrumenter.withProblemClass(SimulationBasedTransitOptimizationProblem.class);
        	instrumenter.withFrequency(1);
        	instrumenter.attachElapsedTimeCollector();
//        	instrumenter.withReferenceSet(null);
//        	instrumenter.attachGenerationalDistanceCollector();
//        	instrumenter.attachHypervolumeCollector();
//        	instrumenter.attachPopulationSizeCollector();
```
2) I am using the NSGA-II for my problem which is obviously multiobjective in nature, but is there a way to measure the performance of the algorithm relative to each individual objective i.e. can I for instance collect runtime performance data for each individual and show by the way of a plot the relationship between both objectives?

3) Is there a parameter to add elitism in the NSGA-II algorithm? or how can I use elitism with NSGA-II in MOEA.

I appreciate your continued assistance.

**Comment by dhadka** [comment]
Hi,

1. Sorry if the guide says you can use the Instrumenter without setting the reference set.  You can use the **Analyzer** with a reference set, but not the Instrumenter.  However, we can use the instrumenter to collect the Pareto fronts, generate the combined reference set, and calculate the metrics later.  See the example code at the end.

2. Sure.  The example code at the end of this message shows how you can get the solutions in the approximation set.  You can then read the objective values and perform this analysis.

3. No.  NSGA-II sorta has elitism already built in.  After creating the offspring, it combines the current population and the offspring and selects the best individuals to survive to the next generation.  As such, the best solution will survive.  However, please note that "best solution" is different for multiple-objectives, since we technically have many "best solutions"...all of the Pareto non-dominated solutions.  The only issue here is if all of the solutions (parents + offspring) are all non-dominated, then we have to eliminate some of them (for NSGA-II, it will use the crowding metric).

----

Here's the code:

```java

		Problem problem = ProblemFactory.getInstance().getProblem("DTLZ2_2");
		String[] algorithms = { "NSGAII", "GDE3" };
		
		Instrumenter instrumenter = new Instrumenter()
				.withProblem(problem)
				.attachApproximationSetCollector();
		
		Executor executor = new Executor()
				.withProblem(problem)
				.withMaxEvaluations(10000)
				.withInstrumenter(instrumenter);
	
		// Store the data and compute the reference set
		Map<String, Accumulator> results = new HashMap<String, Accumulator>();
		NondominatedPopulation referenceSet = new NondominatedPopulation();
		
		for (String algorithm : algorithms) {
			referenceSet.addAll(executor.withAlgorithm(algorithm).run());
			results.put(algorithm, instrumenter.getLastAccumulator());
		}
		
		// Calculate the performance metrics using the reference set
		QualityIndicator qi = new QualityIndicator(problem, referenceSet);
		
		for (String algorithm : algorithms) {
			Accumulator accumulator = results.get(algorithm);
			
			System.out.println(algorithm);
			
			for (int i = 0; i < accumulator.size("NFE"); i++) {
				List<Solution> approximationSet = (List<Solution>)accumulator.get("Approximation Set", i);
				qi.calculate(new NondominatedPopulation(approximationSet));
				
				System.out.print("    ");
				System.out.print(accumulator.get("NFE", i));
				System.out.print(" ");
				System.out.print(qi.getHypervolume());
				System.out.println();
			}
			
			System.out.println();
		}
```

And a snippet of the output:

```
NSGAII
    100 0.14273612253661394
    200 0.1917179300430558
    300 0.2931595084924806
    400 0.3678912497734381
    500 0.4419171480937581
    600 0.4756730285870763
    700 0.500448480434395
    800 0.5406827496099182
    900 0.5536961468909706
    1000 0.564474059726235
    ...
```

**Comment by Nobik2** [comment]
My bad, I read the guide wrong. It is the analyzer and not the instrument that can work without the reference set. Thanks for the code snippet I will use them shortly.


Regards

**Comment by Nobik2** [comment]
@dhadka 

1) When I tried using the code you gave above, I get the error below, so I then try to write a  ProblemProvider for my problem using an the example in section 6.3 of the guide (see code below), but I end up with the same message, could you show how I can modify the code for a custom problem. In my executor I use the `.withProblemClass()` so I have not used the ProblemFactory route.

2) Can you show me how I can implement checkpoints, I need it because my problems runs for a very long time

```java
Exception in thread "main" org.moeaframework.core.spi.ProviderNotFoundException: no provider for SimulationBasedTransitOptimizationProblem
	at org.moeaframework.core.spi.ProblemFactory.getProblem(ProblemFactory.java:159)
	at playground.onnene.ga.RunSimulationBasedTransitOptimizationProblem.main(RunSimulationBasedTransitOptimizationProblem.java:92)
```

```java
public class GA_ProblemProvider extends ProblemProvider {

	@Override
	public Problem getProblem(String name) {		
		if (name.equalsIgnoreCase("SimulationBasedTransitOptimizationProblem")) {
				try {
					return new SimulationBasedTransitOptimizationProblem();
				} catch (FileNotFoundException e) {
					e.printStackTrace();
				}				
		}
		
		else {			
			return null;						
		}
		return null;		
	}
	
	@Override
	public NondominatedPopulation getReferenceSet(String name) 	
		if (name.equalsIgnoreCase("SimulationBasedTransitOptimizationProblem")){		
			try {
				return new NondominatedPopulation(PopulationIO.readObjectives(new File("")));
			} catch (IOException e) {
				throw new FrameworkException(e);
			}			
		}
		else {			
			return null;
		}
	}
		
}
```

**Comment by lmrkela** [comment]
How analyzer works without reference set?
Are combined results from all algorithms used as default reference set for metrics?

**Comment by dhadka** [comment]
@lmrkela 

> Are combined results from all algorithms used as default reference set for metrics?

Yes, if no reference set is given, it will compute an "approximation set" by combining the results from all algorithms and finding the non-dominated solutions.

It doesn't really matter if you're using a reference set or approximation set, the important part is being consistent.  If you're trying to compare several MOEAs, make sure you're using the same reference or approximation set.  Use just one `Analyzer`, add all the results, and compute the result.  Do not use multiple `Analyzer`s, as they could use different approximation sets.
