### ISSUE TITLE
Hypervolume calculation

### ISSUE THREAD

**Issue by YaliWang15** [MOEAFramework/MOEAFramework#182]
Hello,

When I calculate hypervolume, I feel something is wrong, can you check if it is a bug?

Analyzer analyzer = new Analyzer()
				.withProblem(test)
				.includeHypervolume();

I achieved the following two Pareto front. The hypervolume of the first set (0.5102040816326532) is larger than the second set (0.47755102040816333), which means the first set is better. But the second set actually dominates the first set (other solutions are the same besides the bold solutions). It is a minimization problem. 

First set:
**26         151         26**
27         145         27
28         144         28
**28         150         26**
29         143         29
30         142         30
31         141         31
33         140         33

Second set:
**26         150         26**
27         145         27
28         144         28
29         143         29
30         142         30
31         141         31
33         140         33

Thanks a lot!!

**Comment by dhadka** [comment]
Hi.  I believe the issue here is that you aren't providing a reference set explicitly and are calling the analyze method (e.g., `printAnalysis` or `getAnalysis`) twice, once for each set.  As a result, it's using two different reference sets which is why you get the unusual hypervolume numbers.

Try the following, which explicitly sets the ideal and reference points for the hypervolume calculation.  This way, all the sets are normalized the same way and the calculation is consistent.

```java

Analyzer analyzer = new Analyzer()
	.withProblem(testProblem)
	.withIdealPoint(26, 140, 26) // minimum value for each objective
	.withReferencePoint(34, 152, 34) // maximum value + 1 for each objective
	.includeHypervolume();
		
analyzer.add("Set1", set1);
analyzer.add("Set2", set2);
		
analyzer.printAnalysis();
```

Which produces:

```
Set1:
    Hypervolume: 0.5872395833333333
Set2:
    Hypervolume: 0.5989583333333334
```

**Comment by WendiWang** [comment]
Hi, Thank you very much for your response!

I didn't provide a reference set because I have no reference set. The two
solution sets were achieved separately by two different algorithms (nsga2
and nsga3). If I use another algorithm, maybe a different solution set will
be obtained. Under this situation, do you know how I can get correct
hypervolume value of different solution sets to compare the performance of
different algorithms fairly. (Even if I get another solution set, the
hypervolume of the new solution set and previous solution sets are correct.)

Many thanks!

Best regards,



2018-06-14 14:22 GMT+02:00 David Hadka <notifications@github.com>:

**Comment by GreyWoolf** [comment]
Hi Wendi,
Did you find any answers???
I have the exactly same question?
