### ISSUE TITLE
Instrumenter error

### ISSUE THREAD

**Issue by Onnene** [MOEAFramework/MOEAFramework#184]
@dhadka 

Referencing this issue from yesterday #183:

Thanks a lot for all your help, indeed the getMutationHint and getVariationHint methods where both returning `null` (see code below), but I have set them to return my operators i.e `"MyCrossover+MyMutation"` and now it works fine, but if you don't mind, please help me answer these questions below so that I can better understand what is going on.

1) When the above operators returned null, the algorithm ran with the `Executor` below, does it imply that it was not applying the `crossover` and `mutation` operators previously?

2) Am I correct in setting both `getMutationHint` and `getVariationHint` to return the same operator combination i.e `"MyCrossover+MyMutation"` or should `getMutationHint return only `"MyMutation"` while `getVariationHint` returns `"MyCrossover+MyMutation"`?

3) In the `OperatorProvider`, the `crossover` and `mutation` rates were different from the values I specified in the `Executor`, in such a case(I assume this is an error on my part) which of the two takes precedence in the algorithm?

4) In the sample `Instrumenter` code you gave me earlier, the `ProblemProvider` is called before the reference set is created few lines later (after the `Executor `has completed its run), also, the reference set is not written to a file that means the `getReferenceSet()` method will return null since there is no file to read how does this affect the functionality of the algorithm?

5) I did some work sometime back with a single objective GA and a plot of the metrics at the end showed the **`best, worst and average`** runs of the algorithm for each metric, does MOEAframework have that functionality? or is that only applicable to single objective GAs?

**Operator Provider**
```java
public class GA_OperatorProvider extends OperatorProvider {
	
	 @Override
	    public String getMutationHint(Problem problem) {
	        return null;
	    }

	    @Override
	    public String getVariationHint(Problem problem) {
	        return null;
	    }

	    @Override
	    public Variation getVariation(String name, Properties properties, Problem problem) {
	        
	        TypedProperties typedProperties = new TypedProperties(properties);

	        if (name.equalsIgnoreCase("MyCrossover")) {
	            return new Crossover(typedProperties.getDouble("MyCrossover.Rate", 1.0));
	        } else if (name.equalsIgnoreCase("MyMutation")) {
	            return new Mutation(typedProperties.getDouble("MyMutation.Rate", 0.2));
	        }

	        // No match, return null
	        return null;
	    }

}

```

**Executor without Instrumenter**
   ```java
    NondominatedPopulation result = new Executor()
           .withProblemClass(SimulationBasedTransitOptimizationProblem.class)
           .withAlgorithm("NSGAII")
           .withProperty("operator", "MyCrossover+MyMutation")
           .withProperty("MyCrossover.Rate", 0.75)
           .withProperty("MyMutation.Rate", 0.25)
           .withProperty("populationSize", 10)        
           .withMaxEvaluations(10)
           .run();
```

Best Regards

**Comment by dhadka** [comment]
Sure :)

1. Since you set `.withProperty("operator", "MyCrossover+MyMutation")`, you are telling the Executor which operators to use.  If you were to remove this line, it then looks at `getMutationHint` and `getVariationHint` to figure out what operators to use.  Since you were previously returning null, it would fail because it doesn't know which operators are appropriate for your custom type.

2. `getMutationHint` should just return `"MyMutation"`.  It expects an operator requiring only one parent.

3. In your `OperatorProvider`, the crossover and mutation rates are the defaults to use if they are not given elsewhere.  By setting `withProperty("MyCrossover.Rate", 0.75)` in the executor, you are telling it to use 0.75 instead of the default value (1.0).

4. Not having a reference set is fine.  It's only used for computing performance metrics and to produce plots.

5. The Analyzer class provides support for this.  It lets you run multiple "seeds" of an algorithm and computes various statistics.

**Comment by Nobik2** [comment]
Thank you, David!
