### ISSUE TITLE
Error: object not serializable (class: org.moeaframework.core.NondominatedPopulation)

### ISSUE THREAD

**Issue by fchgithub** [MOEAFramework/MOEAFramework#207]
Hi @dhadka  ,
For a part of my code, I need the NondominatedPopulation class to be serialized. To get a general overview of what I am doing, the objects from this class should pass through databricks cluster nodes, therefore it is forced to be serialized and I am not able just to change this class with adding "implements Serializable" since it ends up with different versions of the class and throws out "not deserializable object error". 
Is there any way that this class implements Serializable?

Thanks

**Comment by dhadka** [comment]
Is this exception thrown when serializing a custom Variable class?  If so, you would need to override the serialization behavior of this class.

The basic idea is you will need to define the following methods in your custom Variable class:

    private void writeObject(java.io.ObjectOutputStream out) throws IOException
    private void readObject(java.io.ObjectInputStream in) throws IOException, ClassNotFoundException

The default behavior of `writeObject` is to just call `out.writeObject(this)`, but since your object is not serializable, you'll need to provide the serialization code yourself.  For example, if your object stores the variables x, y, and z, it would look something like:

```
     private void writeObject(java.io.ObjectOutputStream out) throws IOException {
         out.writeInt(this.x);
         out.writeFloat(this.y);
         out.writeObject(this.z); // asumming z is a serializable object
     }
```

And `readObject` works similarly:

```
     private void readObject(java.io.ObjectInputStream in) throws IOException, ClassNotFoundException {
          this.x = in.readInt();
          this.y = in.readFloat();
          this.z = (ClassOfZ)in.readObject();
     }
```

For more details, see the documentation starting at the paragraph "Classes that require special handling...": https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html

**Comment by fchgithub** [comment]
A list of nondominatedPopulation (not any other type of custom class) is passed between cluster nodes!
