### ISSUE TITLE
How to transform MaxGen to maxEvaluations and compare two algorithms with different popsize

### ISSUE THREAD

**Issue by Tesla-Liu** [MOEAFramework/MOEAFramework#24]
Dear David,
I want to repeat the work of NSGA-III to compare it with other algorithms based on MOEA Framework, but I find that the terminal condition used in MOEA Framework is maxEvaluations instead of MaxGen. So, in your opinion, how to transform MaxGen to maxEvaluations?
If the number of objectives(M) is 5, the population size(popsize) is 212, and the terminal condition(MaxGen) is 600, then is the value of maxEvaluations equal to 212 * 600, 5 * 212*600 or another  expression ?
In the paper, the popsize  of NSGA-III and MOEA/D-PBI is different, how to tackle with this situation to compare different algorithms based on MOEA Framework?

**Comment by dhadka** [comment]
The terminal condition is based on maxEvaluations since not all algorithms are generational, or may evaluate a variable number of offspring each iteration.  For most algorithms, however, if you know the population size, then the equation is

    evaluations = iterations * population_size

For algorithms like NSGA-II, NSGA-III, and MOEA/D, this condition holds.  They have a fixed population size.

If you're comparing two algorithms with different population sizes, then you should ensure both algorithms perform the same amount of "work".  In this case, you want `maxEvaluations` to be equal.  One algorithm will just have more iterations, but they will have roughly the same number of evaluations.

**Comment by Tesla-Liu** [comment]
Thanks for your accurate and timely reply!  I think I have got the answer to the first question, but I need more details about the second question.
If I compare NSGA-III with MOEA/D based on MOEA Framework and they have roughly the same number of evaluations, Do I need to ensure most of the individuals in both population are the same?
In Example2, do the three algorithms, NSGA-II, GDE3 and eMOEA, share the same individuals?

**Comment by abdulhameedpk** [comment]
I found the following formula correct for finding MaxGen from MaxEvaluations,
MaxGen = (MaxEvaluations/PoPSize) - 1; so
MaxEvaluations= MaxGen*PopSize + 1

Regarding the 2nd Question: Obviously each algorithm that are called for the same problem (like .withProblem("UF1")) maintain its own set of individuals (copies of problem) in each iteration. You don't need to start each algorithm with the same set of initial solutions.

**Comment by Tesla-Liu** [comment]
@abdulhameedpk @dhadka 
Thanks for your important reply! I have debugged Example2.java in the MOEA Framework and I know each algorithm have its own solution set. However, the matter I concerned, first and foremost, is whether using two population(having roughly the same size) consisting of different individuals is free from side effects or not. For example, I care much about whether the result got by using the above-mentioned population is rigorous enough in academic research.

**Comment by dhadka** [comment]
@Tesla-Liu Solving a problem with two MOEAs (thus having two populations consisting of different individuals) is the correct way to use the software and is free from side effects.

If I understand correctly, you are asking whether it is OK to compare two MOEAs that use different population sizes?  As long as you are not unduly hindering the performance of an algorithm, then it should be OK for academic research.  Just be sure to provide justification (ideally with citations) for the parameterization.  For example, if I were peer reviewing the paper, I would look at how similar the population sizes are.  It's OK if the difference is small (see http://www.egr.msu.edu/~kdeb/papers/k2012010.pdf for an example).  If the difference is large, I would then look at whether the size of the population can affect the performance of the algorithm.  For NSGA-III and MOEA/D, the size of the population, which is in general proportional to the number of reference points / weights, will have an impact.  Fewer reference points can create sparser approximation sets, which can degrade the performance metrics.  In other cases, it's perfectly OK for the population size to differ.  For example, PAES has a population size of 1.  It utilizes a different mechanism to maintain the Pareto approximation (the adaptive grid archive).  As long as both MOEAs are run for the same number of evaluations and both have been configured appropriately for the problem, then the comparison is OK.

**Comment by Tesla-Liu** [comment]
@dhadka  Thanks for your detailed reply! I think it is my topic that makes you understand incorrectly and I apologize for that. Now, please let me describe this question systematically.
When we compare two algorithms, we need two populations (thus having two population sizes) and there may be three kinds of situation about the two population sizes. 
First, the population size of algorithm A is very different from the population size of algorithm B. For example, PAES has a population size of 1 and MOEA/D has a population size of 91. In order to compare  the two algorithms impartially,  we have to use two populations consisting of different individuals and make both algorithms run for the same number of evaluations. You have answered this question.
Second, the two algorithms have roughly the same population size . For example, NSGA-III has a population size of 92 and MOEA/D has a population size of 91. In my opinion, in order to compare  the two algorithms impartially, 91 individuals of NSGA-III must be the same as the 91 individuals of MOEA/D and then we generate one more individual for NSGA-III. Hence I ask you how to  implement this idea based on MOEA Framework. Moreover, if I use two populations consisting of totally different individuals, I doubt whether this experiment is rigorous and whether the result can be recognized by peers. I want you to answer this question. (Both MOEAs are run for the same number of evaluations and both have been configured appropriately for the problem)
Finally, the two algorithms have the same population size. I have no question regarding this situation.

**Comment by Tesla-Liu** [comment]
@dhadka  @abdulhameedpk  I find the data of pf provided by MOEAFramework(v2.7) are exceptional. For example, the point, (0.0, 0.0, 6.0), repeats one hundred times in WFG6.3D.pf and WFG7.3D.pf.

**Comment by dhadka** [comment]
If you want to initialize both algorithms with the same initial solutions (e.g., the same 91 solutions and then one extra random solution for NSGA-III), then you'll need to provide your own Initialization routine.  For example:

    final Solution[] initialSolutions = new RandomInitialization(problem, 91).initialize();

    Initialization initialization = new Initialization() {
            public Solution[] initialize() {
                Solution[] result = new RandomInitialization(problem, populationSize).initialize();
                
                for (int i = 0; i < initialSolutions.length; i++) {
                    result[i] = initialSolutions[i].copy();
                }  

                return result;
            }
    };

This first creates the 91 individuals that will be shared.  Then, the initialization method will return a copy of those 91 solutions plus randomly-generated solutions in the remaining slots.  Next, you'll need to instantiate the two algorithms and pass in this new initialization method to their constructors.  See [StandardAlgorithms.java](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/StandardAlgorithms.java) to see how the algorithms are instantiated.  This is a bit complex because it's not the standard way to use the code, but it is possible.

It's more common in the literature to instantiate the algorithms with randomly-generated initial populations.  See [http://www.egr.msu.edu/%7Ekdeb/papers/k2012010.pdf](http://www.egr.msu.edu/%7Ekdeb/papers/k2012010.pdf) for an example.  The impartial comparison is achieved by repeating this experiment many times (say 50 times) and using statistical hypothesis tests to determine if any difference is statistically significant.

Regarding your comment that the points repeat in the Pareto front file, this is true.  The software reads those files into a NondominatedPopulation, so any duplicate solutions are removed prior computing the performance metrics.

**Comment by dhadka** [comment]
Closing this ticket.  Please open a new ticket if you have other questions.
