### ISSUE TITLE
Random interger value from permutation

### ISSUE THREAD

**Issue by zealrant** [MOEAFramework/MOEAFramework#30]
Hi, I wonder if MOEA support random integer value from permutation.

It means, I want to get 6 random integer from 0 to 52 and anything doesn't same each other. Like lottery.

I read "Integer" and "Permutation" data type part of manual. However, random "Integer" type allow the same number like "11, 11, 12". And "permutation" type is limited by length.

So, I use trick when I make the newSolution like this

```java
@Override
	public Solution newSolution() {
		Solution solution = new Solution(numberOfVariables, numberOfObjectives);
		
		List<Integer>setting = new LinkedList<Integer>();
		for(int j =0;j < NUMBEROFFEATURE; j++){
			setting.add(j);
		}		
		Random random = new Random();
				
		for(int i=0;i< numberOfVariables;i++){
			int x = setting.remove(random.nextInt(setting.size()));
			solution.setVariable(i, EncodingUtils.newInt(x,x));
		}
		
		return solution;
	}
```

However, When I execute like this

```java
NondominatedPopulation result = new Executor()
					.withProblemClass(FeatureSelect.class, numberOfAttribute, NUMBEROFOBJECTIVES)
					.withAlgorithm("NSGAII")
					.withProperty("populationSize", POPULATIONSIZE)
					.withMaxEvaluations(MAXITERATION)
					.distributeOnAllCores()
					.run();
```
Integer Data type has lower and upper bound. 
```error
Exception in thread "main" java.lang.IllegalArgumentException: value out of bounds (value: 11.186, min: 10, max: 11)
	at org.moeaframework.core.variable.RealVariable.setValue(RealVariable.java:102)
	at org.moeaframework.core.operator.real.SBX.evolve(SBX.java:214)
	at org.moeaframework.core.operator.real.SBX.evolve(SBX.java:108)
	at org.moeaframework.core.operator.CompoundVariation.evolve(CompoundVariation.java:130)
	at org.moeaframework.algorithm.NSGAII.iterate(NSGAII.java:85)
	at org.moeaframework.algorithm.AbstractAlgorithm.step(AbstractAlgorithm.java:161)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:700)
	at org.moeaframework.Executor.run(Executor.java:629)
	at MainProcess.main(MainProcess.java:31)
```
I think my solution is not proper. so.. how can I solve it?

**Comment by dhadka** [comment]
This problem is a bit tricky since we do not support a decision variable representation for "selection without replacement".  Your current approach encounters the error since the `newSolution()` is returning different bounds for each solution it creates, which makes it nearly impossible for the variation operators to produce offspring within the bounds.  In general, `newSolution()` should always return the exact same decision variables.

You would either need to reuse an existing type, implement a repair strategy, or define a new decision variable type.  My recommendation is to reuse an existing type.  For example, if you want to pick K unique values from 0 to N-1, pick only the first K values from a permutation of length N:

```java

public Solution newSolution() {
    Solution solution = new Solution(1, numberOfObjectives);
    solution.setVariable(0, EncodingUtils.newPermutation(N));
    return solution;
}

public void evaluate(Solution solution) {
    int[] permutation = EncodingUtils.getPermutation(solution.getVariable(0));
    int[] kvalues = Arrays.copyOfRange(permutation, 0, K);
    // kvalues stores K unique numbers from 0 to N-1
}
```

In the repair strategy, you would start with K integer variables:

```java

public Solution newSolution() {
    Solution solution = new Solution(K, numberOfObjectives);

    for (int i = 0; i < K; i++) {
        solution.setVariable(i, EncodingUtils.newInt(0, N-1));
    }

    return solution;
}
```

Then, in the `evaluate(...)` method, check to see if there are any duplicate values.  If there are duplicates, "repair" the solution by getting rid of the duplicates.  A simple "repair" would be to increment the duplicate value (mod N) until it is unique.  This way, a solution with duplicates, `(5, 1, 2, 2, 8)`, would be converted to `(5, 1, 2, 3, 8)`.

If you want to define a new decision variable type, instructions can be found in the Beginner's Guide.

**Comment by zealrant** [comment]
I appreciate for your clear and quick response.

I solve the problem by repairing solution.
```java
@Override
	public void evaluate(Solution solution) {

		int[] eval = new int[numberOfVariables];
		for (int i = 0; i < numberOfVariables; i++) {
			eval[i] = EncodingUtils.getInt(solution.getVariable(i));
		}
		Set<Integer> test = new HashSet<Integer>(Ints.asList(eval));

		double[] d = new double[2];
		if (test.size() < eval.length) {
			solution = repair(solution, test);
		}
		
		for (int i = 0; i < numberOfVariables; i++) {
			eval[i] = EncodingUtils.getInt(solution.getVariable(i));
		}
		
		try {
			d = evaluator.evaluate(eval);
			d[0] = -d[0];
			d[1] = -d[1];
		} catch (Exception e) {
			e.printStackTrace();
		}

		solution.setObjectives(d);
	}

	private Solution repair(Solution solution, Set<Integer> solutionSet) {
		List<Integer> permu = new LinkedList<Integer>();
		for(int i =0; i < NUMBEROFFEATURE; i++){
			permu.add(i);
		}
		Random random = new Random();
		random.setSeed(System.currentTimeMillis());
		while(solutionSet.size() < numberOfVariables){
			solutionSet.add(permu.remove(random.nextInt(permu.size())));
		}
		EncodingUtils.setInt(solution, Ints.toArray(solutionSet));
			
		return solution;
	}
```
However, It is too slow when select large number K. So, I bought e-book for making new variable type. 
If I block on technical things, I make issue again.

Thanks again.
