### ISSUE TITLE
I cannot get similar experimental results on the DTLZ problems with DBEA implemented in MOEAFramework

### ISSUE THREAD

**Issue by VictorPih** [MOEAFramework/MOEAFramework#32]
Hi, I am a user of MOEAFramework 2.8. I cannot get similar experimental results on the DTLZ problems with DBEA. For example, I run DBEA on DTLZ1 with 3 objectives as follows:

    public static void main(String[] args) throws IOException {

       String[] algorithms = { "DBEA" };

		//setup the experiment
		Executor executor = new Executor()
				.withProblemClass(MyDTLZ1.class)
				.withProperty("populationSize", 91)
				.withMaxEvaluations(36400);

		Analyzer analyzer = new Analyzer()
				.withProblemClass(MyDTLZ1.class)
				.includeInvertedGenerationalDistance()
				.includeHypervolume()
				.withReferenceSet(new File("referenceset/DTLZ1_3.dat"))
				.showStatisticalSignificance();

		//run each algorithm for 30 seeds
		for (String algorithm : algorithms) {
			analyzer.addAll(algorithm, 
					executor.withAlgorithm(algorithm).runSeeds(30));
		}

		//print the results
		analyzer.printAnalysis();

	}
	
	public static class MyDTLZ1 extends DTLZ1 {
		public MyDTLZ1() {
			super(3);
		}
	}

Here are the results:

DBEA:
    Hypervolume: 
        Min: 0.9349984274161561
        Median: 0.9720140968764589
        Max: 0.9733536642529024
        Count: 30
        Indifferent: []
    InvertedGenerationalDistance: 
        Min: 0.19196005821680265
        Median: 0.3259443645886221
        Max: 0.3315151659514037
        Count: 30
        Indifferent: []

The reference set is supported by Dr. Asafuddoula, which is also used in the paper "A Decomposition-Based Evolutionary Algorithm for Many-Objective Optimization." IEEE Transaction on Evolutionary Computation, 2015, 19(3):445-460.
[referenceset.zip](https://github.com/MOEAFramework/MOEAFramework/files/130791/referenceset.zip)

The results reported in the paper are (called I-DBEA in this paper):
![1](https://cloud.githubusercontent.com/assets/17248928/13047727/1b33ba9c-d41c-11e5-8a32-924c5ea6f760.jpg)
![2](https://cloud.githubusercontent.com/assets/17248928/13047729/1e187cde-d41c-11e5-9e68-048bb4f0a481.jpg)

Is there anything wrong? Thank you very much.

**Comment by dhadka** [comment]
Hi @VictorPih 

I suspect the problem lies in their reference set.  If you look at Coello Coello's Evolutionary Algorithms for Solving Multiobjective Problems on page 201, you'll see the reference set is supposed to intersect each axis at (0.5, 0, 0), (0, 0.5, 0), and (0, 0, 0.5).  But in the reference set file from Dr. Asafuddoula, it intersects at (1, 0, 0), (0, 1, 0), and (0, 0, 1).  They might be normalizing the reference set file.  However, that's causing the difference you're observing.

Best Regards,
David

**Comment by VictorPih** [comment]
Thanks for your answer @dhadka 

You are right. Dr. Asafuddoula said the reference sets need to be multiplied by a suitable factor (eg. multiply DTLZ1_3 with 0.5). 

I am looking for suitable reference sets for DTLZ and WFG problems. I want to compute IGD of well-known algorithms with these sets and record the results. Then, I can use these results directly in the future. Is there anything wrong with this idea? 

MOEAFramework provides reference sets for some problems in the pf folder. I wonder if I can use them as standard reference sets. Then, all experiment results based on this sets could be compared directly. By the way, Are the reference sets in MOEAFramework generated by systematic sampling on PF-true?

**Comment by dhadka** [comment]
You're free to use the files in the pf/ folder (they are used by default when computing the performance metrics).  However, depending on what you're trying to do, you may desire sets with fewer/more points.  You can accomplish this in two ways:

Many of the problems (DTLZ, WFG, etc.) have a `generate()` method that produces one randomly-generated solution on PF-true.  You can repeatedly call this method to generate PF-true.  Alternatively, we provide a command-line utility which does the same:

```
java -cp "lib/*" org.moeaframework.analysis.sensitivity.SetGenerator --problem "DTLZ1_3" --numberOfPoints 200 --output my_dtlz1_3d.ref
```

![p1](https://cloud.githubusercontent.com/assets/2496211/13144791/a9e6f63c-d61a-11e5-9cc6-bfd214fe5877.png)

Note that since the points are randomly generated, they are not evenly spread across PF-true.  Also, some problems are biased and will under/oversample regions of PF-true.  To avoid these two issues, you can specify an optional `--epsilon` argument that enables epsilon-dominance.  You should also increase the `--numberOfPoints` to increase the chance of generating solutions from the undersampled regions:

```
java -cp "lib/*" org.moeaframework.analysis.sensitivity.SetGenerator --problem "DTLZ1_3" --numberOfPoints 100000 --epsilon 0.025 --output my_dtlz1_3d.ref
```

![p2](https://cloud.githubusercontent.com/assets/2496211/13144844/f1115fd4-d61a-11e5-891a-40cdac0af561.png)

These points are not systematically sampled (e.g., a grid search), but using epsilons you can generate evenly-spaced points.

**Comment by VictorPih** [comment]
Thanks a lot @dhadka

**Comment by dhadka** [comment]
You're welcome.  Closing the ticket.
