### ISSUE TITLE
Question regarding the setting of "distributeOnAllCores()"

### ISSUE THREAD

**Issue by xiongjuly** [MOEAFramework/MOEAFramework#383]
Dear developers of MOEAFRAMEWORK,

I'm writing to ask a question about the setting of "distributeOnAllCores()". I did a simple test using the optimization question "UF1" (please see the code attached below), and found that if I did not include the setting of "distributeOnAllCores()", the whole optimization would only run 8 seconds, while after I set  "distributeOnAllCores()", the whole optimization would run more than 28 seconds. I wonder why the setting of "distributeOnAllCores()", indeed, decreased the running efficiency, which is really counter-intuitive. 

Look forward to your kind reply!

Code:

                LocalDateTime time_BeforeOpt = LocalDateTime.now();

		NondominatedPopulation result = new Executor()
		.withProblem("UF1")
		.withAlgorithm("NSGAII")
		.withMaxEvaluations(500000)
		.withProperty("populationSize", 1000)
		.withProperty("operator", "sbx+pm")
		.withProperty("sbx.rate", 1) //seems to be more effective to set this parameter as a larger value
		.withProperty("pm.rate", 0.0001) //seems to be more effective to set this parameter as a smaller value
		.distributeOnAllCores()
		.run();
		
		LocalDateTime time_AfterOpt = LocalDateTime.now();
		Duration duration_Opt = 
				Duration.between(time_BeforeOpt, time_AfterOpt);
		System.out.println("duration_Opt: " + duration_Opt.getSeconds());

**Comment by dhadka** [comment]
What you're seeing is known as [parallel slowdown](https://en.wikipedia.org/wiki/Parallel_slowdown) and occurs when the overhead of parallelization outweighs the speedup.

In your specific example with UF1, I measured it spent 0.463 seconds total to evaluate all 500,000 solutions.  That's 0.000000926 seconds per evaluation!  Basically, the overhead needed to distribute the function evaluations is large compared to the time to evaluate the function.

Try editing the UF1 problem to make it artificially run slower.  This can be as simple as adding a loop:

```java

	public void evaluate(Solution solution) {
		double[] x = EncodingUtils.getReal(solution);
		double[] f = new double[2];

		for (int i = 0; i < 10000; i++) {
			CEC2009.UF1(x, f, numberOfVariables);
		}

		solution.setObjectives(f);
	}
```

You might also need to reduce the max evaluations as this will take significantly longer to run.  When I tested this using 5,000 evaluations, the serial case took 30 seconds whereas the distributed case took only 12 seconds.

(In this example, I'm using a 4-core machine.  We would ideally expect a 4x speedup, but we only observe 2.5x speedup.  This is again due to the additional overhead from parallelization preventing us from reaching the optimal speedup.)

**Comment by xiongjuly** [comment]
Thanks for your quick and kind reply!
I got your points. I will try to apply parallelization to my own optimization problem, in which one function evaluation would take around 2 minutes. I would expect that parallelization would speed up the function evaluation in my own case.
