### ISSUE TITLE
Generation based objective function evaluation

### ISSUE THREAD

**Issue by snow54** [MOEAFramework/MOEAFramework#41]
Hello David,

Is there any way to evaluate objective functions by generation but not by individual offspring?  I'm evaluating objective function with an external program by calling it out in an evaluate class.  I would like to do parallelization in the external program.  To do that, I would like MOEA framework to output decision variables of all offsprings in one generation, would like to evaluate objective functions for each offspring, and would like MOEA framework to read objective functions and to evolve the population.

I have read user manual for MOEA framework itself and high performance computing but cannot find a way so far.

Thank you,

**Comment by dhadka** [comment]
Hi,

Great question.  There is no existing way to achieve this, but with some extra code we can create the behavior you're looking for.  First, I created the [MyProblem.java](https://gist.github.com/dhadka/a2db62c209ed1e2d90ef5eb25c9c4110) class.  This will aggregate a given number of solutions, write their decision variables to a file, execute a program, and read their objectives and constraints from an output file.  You will need to modify several methods:

- `getNumberOfVariables()`
- `getNumberOfObjectives()`
- `getNumberOfConstraints()`
- `newSolution()` - To define the types and bounds of your decision variables
- `evaluateAll()` - This is the actual method that writes the input file, calls your executable, and reads the objectives/constraints in an output file

I've provided some example code in the `evaluateAll()` method.  Once you have this file setup, you can then run it as follows:

```java

		NondominatedPopulation result = new Executor()
				.withProblem(new MyProblem(100))
				.withAlgorithm("NSGAII")
				.withProperty("populationSize", 100)
				.withMaxEvaluations(10000)
				.run();
```

This creates a new `MyProblem` instance with the number of solutions it should aggregate before invoking your program.  It's best to set this number equal to your population size...or a factor of the population size.  Otherwise, the code will stall waiting for additional solutions to process.

Hope this helps!

**Comment by snow54** [comment]
Hello David,

Thank you very much for your quick help.  I managed to incorporate your example to my program and it started working.

Thank you for providing such a great software.
