### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zhoudiprivateChina** [MOEAFramework/MOEAFramework#42]
Hi, when i run the Diagnositic Tool to check the performance of the algorithm, it's great!  The changing of the metrics such as GD by the iteration is plotted very clear, but where can i get these data? i mean the line in the image below is drew based on which variable? This variable must contain 25000 GD datas which calculated during the 25000 running.
![image gd](https://cloud.githubusercontent.com/assets/16380025/14270596/4111d3c0-fb22-11e5-8417-f4834108f689.png)

**Comment by dhadka** [comment]
The diagnostic tool unfortunately does not let you export the data currently.  This is something we can look at adding, but it's not currently available.  Instead, I would recommend you use the `Instrumenter`, which gives you access to the raw data shown in these plots.  See [Example3.java](http://moeaframework.org/examples.html#example3) for more details.

**Comment by zhoudiprivateChina** [comment]
Thank you so much, dhadka. But i have another question: when i run the OMOPSO in the WFG1, the hypervolumn=0. How can i get the unzero value as jMetal did?

**Comment by dhadka** [comment]
Which version of jMetal are you comparing against?  I know in the 5.x versions they changed the hypervolume calculation to use the faster WFG hypervolume code and included a large offset (100.0) when calculating the reference point.

I personally don't like using such a large offset as at diminishes the relative value of points close to the Pareto front.  But, I've committed a small change that allows this.  Assuming you are working on a clone of the git repository:

1. Pull the latest changes on Git
2. Edit `global.properties`.  Add the line `org.moeaframework.core.indicator.hypervolume_delta = 10`.  If your nadir point is (a, b), then the reference point will be (10 * a, 10 * b).  You can adjust the delta factor as needed.
3. Run the analysis; you should see more non-zero values since the reference point has been offset

If you're using the compiled JAR files instead, download the [latest code from the Git repo](https://github.com/MOEAFramework/MOEAFramework/archive/master.zip) and run the ant build script to compile the JARs.  Overwrite your old JARs with the new ones from the dist/ folder.  Then follow steps 2 and 3.
