### ISSUE TITLE
Interpretation of sensitivity values of MOEAFramework

### ISSUE THREAD

**Issue by abdulhameedpk** [MOEAFramework/MOEAFramework#43]
Dear David.
             I have some questions regarding the analysis feature of MOEAFramework. My questions are,
**Q1.** How to interpret the sensitivity values? For instance in your manual, you interpret the following result 
Total-Order Effects
        populationSize 0.49 [0.06]
        maxEvaluations 0.83 [0.05]

as, populationSize has  49%  and maxEvaluations has 83% impact on performance variations. I am confused with %impact as the total impact exceeds 100%.

**Q2.** In your paper titled "_Diagnostic Assessment of Search Controls and Failure Modes in Many-Objective Evolutionary Optimization"_,  does the Interaction plots (Fig. 8 and Fig. 9) represents the Total-Order-Effects or something else?

**Q3.** How do I found tune values for a parameter of an algorithm once it know that I has the largest impact on performance variation?

**Q4.** What does the negative values (and values greater than 1) for sensitivities indicate? 

For some parameters in my problem, the First-Order effect is negative while its total order effect is significant (more than 1). How I should interpret such values?. An example is shown in following,

---

Sobol sensitivities for SMPSO
Parameter   Sensitivity [Confidence]
First-Order Effects
  maxEvaluations 0.20411833679576594 [0.9710250715772006]
  populationSize 0.009810565653358113 [1.1954395038133685]
  **pm.rate -0.0774521157999056** [1.3290191838926941]
  archiveSize -0.04253429096781094 [1.650050745079512]

Total-Order Effects
  maxEvaluations 0.766893007622266 [1.8585916853546982]
  populationSize 1.3510018510737352 [3.213105864346599]
**pm.rate 1.559230345596764** [13.544732893862083]
  archiveSize 1.4957291118178269 [5.236133482453727]

Sobol sensitivities for GDE3
Parameter   Sensitivity [Confidence]
First-Order Effects
  maxEvaluations 0.5610428919939311 [1.6997347547313777]
  populationSize 0.012648975989543643 [1.8204003256626513]
  de.crossoverRate -0.12668936256528554 [1.6177896930507827]
  de.stepSize 0.3155205001839396 [1.9809204625062204]

Total-Order Effects
  maxEvaluations 0.9573251069632154 [6.196519873584054E15]
  populationSize 0.7737552764734495 [1.205632455794854E15]
  de.crossoverRate 0.8125865127820031 [2.0610090448631568E15]
  de.stepSize 0.9932573056752287 [1.3235108342241098E15]

**Comment by dhadka** [comment]
Hi, great questions.

Q1) Since the total-order indices sum up all first and interactive effects, there is overlap between the total-order sensitivities.  For example, the total-order index of populationSize includes the first-order effects for populationSize plus the second-order effects for populationSize AND maxEvaluations.  Likewise, the total-order effects for maxEvaluations also includes this second-order effect.  If you add all the total-order indices, they will typically exceed 100% unless there are no interactive effects.

Q2) Yes, the interactive effects are the total-order effects.

Q3) You could search the resulting datasets to find which parameterization produces the best result.  For example, after running `ResultFileEvaluator`, each row in the output corresponds to a row in the samples file.  You can also use the `SimpleStatistics` class to average the metrics if you ran multiple seeds.

Q4) The Sobol analysis generally requires thousands or even tens of thousands of samples to produce accurate results.  Negative values and those exceeding 1.0 are due to sampling errors when the Sobol method is approximating the sample variance.  Generally these errors are reduced as the sample size increases.  I would suggest looking at increasing the sampling first.  You could also consider a different sensitivity analysis method that works better with smaller sample sizes.  Check out [SALib](https://github.com/SALib/SALib), which was written by some of my colleagues.  It's Python, but you can use SALib to produce your sample files, evaluate them using the MOEA Framework, then feed the resulting metrics back to SALib to compute the sensitivities.

On a side note, we've found that it's generally better to use the ranking of Sobol sensitivity indices rather than the sensitivity value itself.  The ranking of which parameter has the 1st largest, 2nd largest, etc. sensitivity is more stable than the sensitivity indices themselves.

**Comment by abdulhameedpk** [comment]
Thanks Dr. David for a quick replay.

How can I print the parameter's rank ordering calculated by the Sobol analysis?

**Comment by dhadka** [comment]
The software currently doesn't display rank ordering.  We've always just manually determined the rankings for our analysis.
