### ISSUE TITLE
How to run NSGA-III?

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#48]
Hi, David, I'm trying to run DTLZ with NSGA-III, I just use example1 with small modifications.Just like this:
NondominatedPopulation result = new Executor()
				.withProblem("DTLZ1-3")
				.withAlgorithm("NSGAIII")
				.withMaxEvaluations(30000)
				.run();
But I found it runs using NSGA-II instead of NSGA-III, so how to use NSGA-III ? I want to find the code of NSGA-III but failed. Thanks for your help.

**Comment by dhadka** [comment]
Hello,

To reuse existing functionality and avoid duplicate code, NSGA-III is implemented as a modified version of NSGA-II with three major changes:

1. A different selection operator for crossover/mutation.  For unconstrained problems, Deb and Jain suggest randomly selecting points from the population since they will most likely all be non-dominated.

2. The `ReferencePointNondominatedSortingPopulation`, which implements NSGA-III's reference points for survival selection.

3. Different default values for the SBX and PM operators.  Deb and Jain suggest using larger distribution indices than commonly used in other algorithms.

So yes, it is using the `NSGAII` class but it's configured in a way that it's actually running NSGA-III.  You can find the code for creating NSGA-III in [StandardAlgorithms.java](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/StandardAlgorithms.java#L358).

Best Regards,
Dave

P.S. If you find that it's truly running NSGA-II without these modifications, please let me know and I can investigate further.

**Comment by longmeili** [comment]
Great thanks for your detailed answer, I have found what I need by now. You can close this issue.
