### ISSUE TITLE
How to produce the true pareto front for problems DTLZ1-DTLZ7

### ISSUE THREAD

**Issue by HuangkeChen** [MOEAFramework/MOEAFramework#49]
The MOEA framework has provided some true pareto front in the folder pf, which is useful. But, the point number of the sample true pareto front is about one hundred, which is less. How to generate the pareto front according to the number of samples？ Thanks very much!

**Comment by dhadka** [comment]
Problems implementing the [AnalytcalProblem](http://moeaframework.org/javadoc/org/moeaframework/problem/AnalyticalProblem.html) interface can be used to generate the true Pareto front.  Each call to `generate()` produces one random Pareto optimal solution.  For example, you can run:

```java

DTLZ2 problem = new DTLZ2(3);
Population trueParetoFront = new Population();

for (int i = 0;  < 1000; i++) {
    trueParetoFront.add(problem.generate());
}
```

Because the solutions are generated randomly, they may not be evenly spaced across the Pareto front.  This is particularly true for biased problems.  One way to deal with this is to generate many thousand solutions and put them into a [NondominatedSortingPopulation](http://moeaframework.org/javadoc/org/moeaframework/core/NondominatedSortingPopulation.html) and truncate the population to a smaller size, or add them to an [EpsilonBoxDominanceArchive](http://moeaframework.org/javadoc/org/moeaframework/core/EpsilonBoxDominanceArchive.html) which uses epsilon-dominance to ensure an even distribution of solutions.

Rather than coding this yourself, there's a utility that already performs this function called the [SetGenerator](http://moeaframework.org/javadoc/org/moeaframework/analysis/sensitivity/SetGenerator.html).  You run this from the command line with the following command:

```
java -cp "lib/*" org.moeaframework.analysis.sensitivity.SetGenerator -b DTLZ2_2 -n 10000 -e 0.01,0.01 -o DTLZ2.2D.pf
```

This will generate 10000 Pareto optimal solutions for 2D DTLZ2 and add them to an epsilon-dominance archive with epsilons set to (0.01, 0.01).  You can then decrease or increase the epsilons until you generate the desired number of points for your reference set.

**Comment by dhadka** [comment]
Just another note: the above method is designed to work on any problem where you can generate Pareto optimal points.  For the DTLZ problems, you can also generate them by hand (although this may be more complicated than just using the examples above).  For example, on DTLZ2, any optimal solution will have the first K-M+1 decision variables set to 0.5.  The remaining M-1 variables can be anywhere between 0 and 1.  If you sample these remaining M-1 variables, you will generate points across the true Pareto front.

**Comment by HuangkeChen** [comment]
Excellent! Thank you very much!

**Comment by yuxb111** [comment]
Hello, How to use similar method :java -cp "lib/*" org.moeaframework.analysis.sensitivity.SetGenerator -b DTLZ2_2 -n 10000 -e 0.01,0.01 -o DTLZ2.2D.pf
to  generate WFG pareto front?Thank you. Happy coming Thanksgiving Day.

**Comment by iostream6** [comment]
Thank you very much David. Your explanations were clear and very helpful.

**Comment by lfarizav** [comment]
Go to https://github.com/lfarizav/NSGA-III/tree/master/real_front and download the true pareto fronts from DTLZ1 to DTLZ4 (3,5,8,10 dimensional cases). Also IDTLZ1 for 3 and 5 dimensional cases.

**Comment by Mathi50** [comment]
Hi, How to get pareto front for DTLZ1 and DTLZ2 with 2 to 3 objectives using MATLAB?
