### ISSUE TITLE
How to calculate the Hypervolume of Knapsack problem using Analyzer?

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#50]
Dear David,
I am trying to use Analyzer to calculate the Hypervolume of Knapsack problem results. The problem instance is read from file and run with NSGA-II.The screenshot is shown below. It seems that the Analyzer cannot getProblemInstance() of Knapsack problem. How can I calculate the Hypervolume? By the way, Hypervolume needs a reference point, how to set it ? Thanks in advance.

![queation](https://cloud.githubusercontent.com/assets/15227853/15711249/93c1d3fa-280d-11e6-81fa-80ef971beaa3.png)

**Comment by dhadka** [comment]
This is failing because it's trying to read from the input file twice, but the input is closed after it is used the first time.  The quick solution is to create one Knapsack instance shared by the Executor and Analyzer:

```java

		// open the file containing the knapsack problem instance
		InputStream input = Knapsack.class.getResourceAsStream(
				"knapsack.100.2");
		
		if (input == null) {
			System.err.println("Unable to find the file knapsack.100.2");
			System.exit(-1);
		}
		
		Knapsack knapsack = new Knapsack(input);
				
		// solve using NSGA-II
		NondominatedPopulation result = new Executor()
				.withProblem(knapsack)
				.withAlgorithm("NSGAII")
				.withMaxEvaluations(50000)
				.run();
		
		new Plot().add("NSGAII", result).show();
		
		Analyzer analyzer = new Analyzer()
				.withProblem(knapsack)
				.includeHypervolume();

		analyzer.add("NSGAII", result);
		
		analyzer.printAnalysis();
```

The Analyzer looks in several locations to obtain a reference point, essentially:

1. Did the user explicitly provide an ideal and/or reference point?
2. Did the user explicitly provide a reference set file?
3. Does the problem define a default reference set?
4. Create a reference set by merging all sets included in the analyzer.

For example, here I set the ideal and reference point explicitly.  Note how the values are negative since we're dealing with maximized objectives.  **This capability was added in the last release (version 2.10), so please make sure you've upgraded to the latest version.**

```java

		Analyzer analyzer = new Analyzer()
				.withProblem(knapsack)
				.withReferencePoint(-3000, -3000)
				.withIdealPoint(-4500, -4500)
				.includeHypervolume();
```

**Comment by longmeili** [comment]
Got it, thanks for your help!

**Comment by dhadka** [comment]
You're welcome!
