### ISSUE TITLE
Initialize Population

### ISSUE THREAD

**Issue by pitangui-cristiano** [MOEAFramework/MOEAFramework#51]
Dear all,

I read the topic from @Naomilicious about the same doubt, but I was unable to solve my problem: I just want to initialize the population with predefined values. The simplest (but apparently the wrong) way that I found was to modify the newSolution() method. 

To test my solution i build a simple code. Basically, I have a 10000 positions boolean string that I set to be all true in the newSolution method - the for printing it in this method prints 10000 trues, so it is correct! However, when I print the solution in the evaluate(Solution solution) method, it prints a random numbers of true and false (bellow is my code). 

Is there a way to initialize the population? Should I use a specific method for it? 

Thanks in advance!

Regards!

public Solution newSolution() 
{
        Solution solution = new Solution(1, 2, 1);  
        solution.setVariable(0, EncodingUtils.newBinary(10000));  
        boolean [] bol = new boolean[10000];             

```
            for(int i = 0; i < 10000; i++)
    {
        bol[i] = true;               
    }

    EncodingUtils.setBinary(solution.getVariable(0), bol);           
    boolean [] solucao = EncodingUtils.getBinary(solution.getVariable(0));

    for(int i = 0; i < 10000; i++)
    {
                    System.out.println(solucao[i]);
    }
 }               
     return solution;
```

}

public  void evaluate(Solution solution) 
{
    boolean [] solucao = EncodingUtils.getBinary(solution.getVariable(0));

```
for(int i = 0; i < 10000; i++)
{
    System.out.println(solucao[i]);
}
```

}

**Comment by dhadka** [comment]
The `newSolution()` method only defines the "prototype" for a solution.  It only defines what a solution looks like, such as the type of variables and their bounds.  Initialization is performed by the [Initialization](http://moeaframework.org/javadoc/org/moeaframework/core/Initialization.html) class.  By default, [RandomInitialization](http://moeaframework.org/javadoc/org/moeaframework/core/operator/RandomInitialization.html) is used, which is why your predefined values are being overridden with random values.

Chapter 5 in the [Beginner's Guide to the MOEA Framework](http://moeaframework.org/documentation.html) covers the topic of customizing algorithms in depth, including defining new initialization procedures.  The gist of it is you need to replace the `RandomInitialization` class with another version that will use your predefined values.  For example, here is how one would construct NSGA-II:

```java

		Initialization initialization = new RandomInitialization(
				problem,
				100);

		TournamentSelection selection = new TournamentSelection(2, 
				new ChainedComparator(
						new ParetoDominanceComparator(),
						new CrowdingComparator()));

		Variation variation = new GAVariation(
				new SBX(1.0, 25.0),
				new PM(1.0 / problem.getNumberOfVariables(), 30.0));

		Algorithm algorithm = new NSGAII(
				problem,
				new NondominatedSortingPopulation(),
				null, // no archive
				selection,
				variation,
				initialization);
		
		while (algorithm.getNumberOfEvaluations() < 10000) {
			algorithm.step();
		}

		NondominatedPopulation result = algorithm.getResult();
```

Instead of `RandomInitialization`, the [InjectedInitialization](http://moeaframework.org/javadoc/org/moeaframework/core/operator/InjectedInitialization.html) class can be used to inject predefined solutions into the initial population.  Any remaining slots in the population will be filled with randomly-generated solutions.

**Comment by pitangui-cristiano** [comment]
Thanks Davidi!

You can close this topic.

Regards!
