### ISSUE TITLE
How to get seed for a run?

### ISSUE THREAD

**Issue by abhinavgaur** [MOEAFramework/MOEAFramework#65]
Hello David,

Thanks for helping me understand the `Collector` class and its function in order to be able to write the whole population in files. I have more questions given below. 

I understand that I can run an algorithm with multiple seeds using `Executor.runSeeds(int nseeds)` but I wish to record the seed values being used in each run so that I can reproduce the same results. I tried by writing a `for` loop with `Executor.withProperty("seed", <some number in 0-1>)` but it didn't work. I also noticed something odd. So I have two questions.

1) How to `get` or `set` the `seed` value for an algorithm run?

2) I noticed that the command `Executor.withProperty("key", <valid value>)` is ignored if the attribute `key` is not present in the hashmap of `Executor`. But I expect it to produce an `invalidKeyException` of sorts in that case. How to achieve that?

Let me know if my second question doesn't make sense as I have made that up from my partial understanding of the code.

Thanks

**Comment by dhadka** [comment]
Thanks for the questions.

1. Call `PRNG.setSeed(...)` followed by `Executor.run()`.  This will perform one run with the given seed.

2. Yes, this is a current limitation that I plan to fix in the next major release.  The tricky part here is that the MOEA Framework uses a plug-in architecture so new algorithms and operators can be introduced dynamically.  Additionally, the available properties could change if, for example, the user selects a different crossover/mutation operator.  There are two ways I can think of to fix this.  (1) Add the ability to detect if a key is not read.  This could be achieved by overriding the `Properties#getProperty(String key)` method and recording which keys are processed.  (2) Add a method that allows an algorithm to list its supported properties.  For each property, we could also include type information, lower/upper bounds, documentation, etc.  This would allow validation of all properties.  I plan to implement (b) in the next major release.

**Comment by abhinavgaur** [comment]
Thanks for the replies David. Yes, I think solution (2) makes sense.  My followup question/suggestion are below.

Question1) To make sure if I am making changes to a valid `key` attribute for an algorithm, I need to check the class file particular to the algorithm? For example, to make sure that `sbx` is indeed a property of `NSGA-II` (and not `SBX`), I should check the `NSGAII.java` file?

Question2) How do I check the default settings (e.g population size, P_cross, P_mut etc) and attribute `keys` (e.g if sbx is used instead of uniform crossover) for any existing implementation of an algorithm in MOEA-fw? In case of `NSGA-II`, I could not find this information in the Appendix-A, page-138 of the guide. The only default parameter value for `NSGA-II` mentioned there is the `populationSize`.

Question3) In a random run of `NSGA-II` using MOEA-fw, I noticed that it doesn't complain even if the population size is a odd number. I couldn't understand this part. This is because for `Tournament Selection` to work on a population, don't we need a population size being a multiple of 2?

Suggestion) I hope that upon implementing the solution (2) mentioned in your reply, the modifying of algorithms still stays similar to as explained in Section-5.3 of the MOEA guide.

Thanks

**Comment by dhadka** [comment]
**Question 1)** Due to separating operators and algorithms, you need to look in several locations to locate the parameters.  Generally, the two spots are `StandardAlgorithms.java` and `StandardOperators.java`.  These two files contain the "built-in" algorithms and operators.  For example, NSGA-II is instantiated [here](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/StandardAlgorithms.java#L329) (also copied below):

```java

	private Algorithm newNSGAII(TypedProperties properties, Problem problem) {
		int populationSize = (int)properties.getDouble("populationSize", 100);

		Initialization initialization = new RandomInitialization(problem,
				populationSize);

		NondominatedSortingPopulation population = 
				new NondominatedSortingPopulation();

		TournamentSelection selection = new TournamentSelection(2, 
				new ChainedComparator(
						new ParetoDominanceComparator(),
						new CrowdingComparator()));

		Variation variation = OperatorFactory.getInstance().getVariation(null, 
				properties, problem);

		return new NSGAII(problem, population, null, selection, variation,
				initialization);
}
```

You can see it read the `"populationSize"` parameter on the second line.  The operators are instantiated by the `OperatorFactory`, which will find the default operators in the `StandardOperators.java` plugin.  For a real-valued problem, it defaults to SBX and PM.  You can find the initialization code [here](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/core/operator/StandardOperators.java#L285):

```java

		if (name.equalsIgnoreCase("sbx")) {
			return new SBX(
					typedProperties.getDouble("sbx.rate", 1.0), 
					typedProperties.getDouble("sbx.distributionIndex", 15.0),
					typedProperties.getBoolean("sbx.swap", true),
					typedProperties.getBoolean("sbx.symmetric", false));
		} else if (name.equalsIgnoreCase("pm")) {
			return new PM(
					typedProperties.getDouble("pm.rate", 
							1.0 / problem.getNumberOfVariables()), 
							typedProperties.getDouble("pm.distributionIndex", 20.0));
		}
```

**Question 2)** In addition to the locations in the code mentioned above, you can also use the book to locate the default values.  First look in Appendix A for the algorithm-specific parameters.  Then figure out what decision variable types are used on the problem.  For example, real-valued variables will use SBX and PM by default.  Then look in Appendix C to find the parameters for these operators.

**Question 3)** In the reference implementation of NSGA-II (by Deb et al.), the population size must be a multiple of 2.  This is primarily due to the crossover operator (SBX) requiring 2 parents.  In the MOEA Framework, it's possible the user selects an operator with a different number of parents, and so it has been designed to handle such cases.  The essential difference is the MOEA Framework uses "selection with replacement" whereas Deb's reference implementation uses "selection without replacement".  This can result in a very small difference in overall performance (e.g., a slightly different hypervolume).  I could help create a version that mimics Deb's version if you're interested in that.

**Suggestion)** It would depend on how much information is provided.  If we supply parameter types, lower/upper bounds, default value, etc., then it would require some changes but they should be minor.  It would likely look like:

```java

PropertyDescriptor[] getSupportedProperties(Problem problem) {
    return new PropertyDescriptor[] {
        new IntegerPropertyDescriptor("populationSize", 2, 10000, "Population Size, default is 100"),
        new RealPropertyDescriptor("sbx.rate", 0.0, 1.0, "SBX Rate, default is 1/N"),
        ...
    }
}
```

**Comment by abhinavgaur** [comment]
Thanks for the detailed reply. expanding on Question3, 

Q3.1) Can you cite some paper that shows the difference between the two approaches, namely "selection with replacement" and "selection without replacement". 

Q3.2) By "different" hypervolume, do you mean better or worse and for which one? 

Q3.3) Is "selection without replacement" expected to perform better in terms of diversity as I am guaranteed to use all population members in that case.

Q3.4) I would appreciate if you can help me create a NSGA-II version that mimics Deb's version of "selection without replacement".

Cheers, Appreciate all the help.

Abhinav

**Comment by dhadka** [comment]
Abhinav,

Q3.1) I'm not aware of any paper, but there could be one from the early days of GA theory.

Q3.2) Further testing using a statistical test (Mann Whitney U test) shows the hypervolumes are statistically identical (see results at end of this comment).

Q3.3) I think "selection without replacement" would offer better diversity for the crossover operator as it ensures all parents are selected.  I'm not sure if it would offer better diversity in terms of the next generation population.  For example, if "selection with replacement" skips a parent, that parent could still survive to the next generation where it would again be an eligible parent.  Haven't thought too much about this though...

Q3.4) A version is posted on the `nsgaii_original` branch.  Here's some sample code for testing:

```java

		String problem = "UF1";

		//setup the experiment
		Executor executor = new Executor()
				.withProblem(problem)
				.withMaxEvaluations(10000);

		Analyzer analyzer = new Analyzer()
				.withProblem(problem)
				.includeHypervolume()
				.showStatisticalSignificance();
		
		analyzer.addAll("NSGA-II with Replacement", executor.withAlgorithm("NSGA-II").withProperty("withReplacement", true).runSeeds(50));
		analyzer.addAll("NSGA-II without Replacement", executor.withAlgorithm("NSGA-II").withProperty("withReplacement", false).runSeeds(50));

		//print the results
		analyzer.printAnalysis();
```

Outputs:

```

NSGA-II with Replacement:
    Hypervolume: 
        Min: 0.30427442639158414
        Median: 0.4749572205650822
        Max: 0.5400080699382166
        Count: 50
        Indifferent: [NSGA-II without Replacement]
NSGA-II without Replacement:
    Hypervolume: 
        Min: 0.3526852677000911
        Median: 0.4864742474917809
        Max: 0.5388136392072161
        Count: 50
        Indifferent: [NSGA-II with Replacement]
```

**Comment by abhinavgaur** [comment]
Thanks for the help.

**Comment by abhinavgaur** [comment]
Hi David,

Sorry had to reopen this issue to ask a followup question. 

In the last reply of Q3.4, you wrote, "A version is posted on the nsgaii_original branch. Here's some sample code ......". I noticed that, just with MOEAfw-2.10 downloaded from [MOEA website](https://github.com/MOEAFramework/MOEAFramework/releases/download/v2.10/MOEAFramework-2.10-Source.tar.gz) (assuming it to be in sync with the `master` branch on Github), I can switch to the "withoutReplacement" version of NSGA-II using `Executor().withProperty("withReplacement", false).run()`. 

I didn't understand why I will need to use the `nsgaii_original` branch instead of `master` branch for the same.

**Comment by abhinavgaur** [comment]
Ok I got it.
