### ISSUE TITLE
Integrate Faster Non-dominated Sorting Methods

### ISSUE THREAD

**Issue by Proteek** [MOEAFramework/MOEAFramework#70]
How can I integrate faster non-dominated sorting methods into the source code and test their running time performance? I want to test several sorting methods instead of using the brute-force one inside standard algorithms like NSGA-III. Thank you.

**Comment by dhadka** [comment]
You could extend the [NondominatedSortingPopulation](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/core/NondominatedSortingPopulation.java) class.  This class is responsible for updating the ranking and crowding attributes of its contents.  Then, since it's a subclass of the `NondominatedSortingPopulation`, you can pass it to the [NSGAII](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/NSGAII.java#L79) constructor.

```java

NSGAII algorithm = new NSGAII(problem,
        new FasterNondominatedSortingPopulation(),
        ...);
```

The design of the faster algorithm will affect how you implement it.  For example, if the algorithm calculates the rank/crowding for all members of the population, then you can simply override the [`update()`](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/core/NondominatedSortingPopulation.java#L228) method.  This should re-compute the rank/crowding attributes for all solutions in the population.  Be sure to set `modified=false` within this method so it knows the attributes are up-to-date.

If the algorithm can update the rank/crowding every time a solution is added or removed, then you would want to override the appropriate methods, such as `add(...)`, `remove(...)`, etc.

Hope this helps!

**Comment by Proteek** [comment]
Thank you for your quick reply. I was able to replace the update method of  NondominatedSortingPopulation. Implementing other subclass seems hard because there are some places where NondominatedSortingPopulation is used, so I have to replace those by FasterNondominatedSortingPopulation. I saw the update() method is called in some awkward places (at least it seems), for example update() is called when it is looping over the population. I want to understand that well, because then it might have more running time. I appreciate your reply. Thanks.

**Comment by Proteek** [comment]
Can you explain me that a little bit? Thank you very much.

**Comment by dhadka** [comment]
Sure.  The `NondominatedSortingPopulation` tracks modifications via the `modified` variable.  This ensures that `update()` is only called when the population is modified (e.g., a solution is added or removed) and needs to calculate new rank/crowding attributes:

```java

		if (modified) {
			update();
		}
```

So if you're looping over the population:

```java

		for (Solution solution : population) {
			...
		}
```

`update()` will only be called once...the first time you try to access a solution in the population.  The loop (an iterator) uses the `get(int index)` method to read each solution.  For the first iteration of the loop, `modified=true` which will trigger `update()`.  Within the `update()` method we set `modified=false`. Therefore, subsequent iterations of the loop will not call `update()`.  Does that make sense?

You could quickly test this by adding a print statement inside your `FasterNondominatedSortingPopulation` class to see how frequently it gets called.  For example, NSGA-II with a population size of 100 and a maximum NFE of 1,000 should only call `update()` 10 times, once per generation.

**Comment by Proteek** [comment]
Thanks a lot. I was also thinking about the same thing. I actually changed the update method of NondominatedSortingPopulation instead of creating a subclass. Hopefully our faster non-dominated sorting method reduce the algorithm practical running time for larger population. Thank you for your code.

**Comment by dhadka** [comment]
You're welcome.  If you're willing to share once your faster method is published, please consider contributing it back into this code.  Thanks!

**Comment by Proteek** [comment]
Sure. I would love to. Thank you very much.

**Comment by Proteek** [comment]
Hello. I am trying to find one/two real world many objective problem so that I can run faster non-dominated sorting algorithm. Do you know any such problem? Do you have the code in MOEAFramework? 

Thanks a lot.
