### ISSUE TITLE
How to use MOEA/D to solve problems of binary decision variables ?

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#71]
Hi, David, to my understanding in this framework MOEA/D doesn't support problems of binary decision variables, such as knapsack problem. How can I use MOEA/D for knapsack problem? Thanks in advance.

**Comment by dhadka** [comment]
You should be able to support other operators by changing lines 496-497 in [`StandardAlgorithms.java`](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/algorithm/StandardAlgorithms.java#L496) from

```java

		Variation variation = OperatorFactory.getInstance().getVariation(
			"de+pm", properties, problem);
```

to

```java

		Variation variation = OperatorFactory.getInstance().getVariation(
			null, properties, problem);
```

This change will enable auto-detection of the decision variable type and will automatically select the default operator(s) for that type.  For binary, it will use HUX+BF (half-uniform crossover with bit flip mutation) by default.

Note: With this change, if you try to solve a real-valued problem, it will default to SBX+PM (simulated binary crossover with polynomial mutation) instead of differential evolution.

**Comment by longmeili** [comment]
Thank you. I tried and it worked. Now I have another question, I want to compare the results got from MOEAFramework with the results published by the author. 
For knapsack problems, the author published  all Pareto-optimal objective vectors in http://www.tik.ee.ethz.ch/sop/download/supplementary/testProblemSuite/, how to load the file data and compare Hypervolume with MOEAFramework results? The author also published results of earlier algorithms, is it possible to load results from file and use Analyzer to compare, such as showStatisticalSignificance?

**Comment by longmeili** [comment]
Thanks, no more questions. This issue can be closed now.
