### ISSUE TITLE
How to collect and plot runtime dynamics of several runs?

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#88]
Hi, David, in your Beginner's Guide you showed how to collect runtime dynamics and plot the result of a single run. I want to know how to do that with several runs, just like in the Diagnostic Tool. By the way, how to add new problem and new algorithms to the  Diagnostic Tool? Thanks in advance.

**Comment by dhadka** [comment]
Hi, I don't think there's a similar way to create the plots like you see in the Diagnostic Tool using a similar approach as shown in the Beginner's Guide.  However, since both use JFreeChart, with a little effort you should be able to create something similar.  The plotting code in the Diagnostic Tool can be found in [LinePlot.java](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/analysis/diagnostics/LinePlot.java), specifically in the [update](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/analysis/diagnostics/LinePlot.java#L223) and  [generateQuantileSeries](https://github.com/MOEAFramework/MOEAFramework/blob/master/src/org/moeaframework/analysis/diagnostics/LinePlot.java#L162) methods.  In the `update` method, you'll find all the code to create the JFreeChart.  It uses the `generateQuantileSeries` to produce the deviation plot (showing the 25-50-75 quantiles).

Information on adding new problems and algorithms can be found in sections 6.2 and 6.3 in the Beginner's Guide.  The basic idea is as follows.  You'll first need to create provides for the new algorithm or problem by implementing an `AlgorithmProvider` or `ProblemProvider`.  These classes are responsible for creating a new instance of your algorithm or problem (more details can be found in Chapter 5).  Second, as shown below, register the new providers with the MOEA Framework.  Finally, you need to override the MOEA Framework's settings to tell it to show the new algorithm or problem within the diagnostic tool.  The code should look something like:

```java

	public static void main(String[] args) throws Exception {
		AlgorithmFactory.getInstance().addProvider(new CustomAlgorithmProvider());
		ProblemFactory.getInstance().addProvider(new CustomProblemProvider());
		
		Settings.PROPERTIES.setString(
				Settings.KEY_DIAGNOSTIC_TOOL_ALGORITHMS,
				"CustomAlgorithm, NSGAII, GDE3");
		
		Settings.PROPERTIES.setString(
				Settings.KEY_DIAGNOSTIC_TOOL_PROBLEMS,
				"CustomProblem");
		
		LaunchDiagnosticTool.main(args);
	}
```

**Comment by dhadka** [comment]
Closing issue.  Please reopen or create a new issue if you have any further questions.
